### ISSUE TITLE
Relive

### ISSUE THREAD

**Issue by TobiX** [voc/plugin.video.media-ccc-de#24]
Add support for Relive (when available).

Discovery: http://cdn.c3voc.de/relive/index.json
Fetch:  https://cdn.c3voc.de/relive/35c3/index.json

**Comment by probonopd** [comment]
This would be really useful. How hard would it be?

**Comment by TobiX** [comment]
Probably not much harder then the "live" part:
- Create a data model
- Write some simple tests
- Wire it all to the URL routing code
- Create a new menu entry for it

Just needs someone motivated to do it 😉

**Comment by probonopd** [comment]
Ah, so it's definitely more than copying something and changing out 2 URLs.

**Comment by master-lincoln** [comment]
I gave it a try and have a PR open for basic support that tries to match conference names with the `project` property on the relive index and lists them under the conference if they are unreleased yet.

**Comment by probonopd** [comment]
Tested, works for me :+1: 
Thank you very much. Highly appreciated.
