### ISSUE TITLE
[Android] Addon is loading content/lists awfully slowly

### ISSUE THREAD

**Issue by x2k13** [voc/plugin.video.media-ccc-de#27]
I've been using this great addon for quite a while with LibreELEC (Krypton, then Leia) on a RPi 3B+ without any serious issues.

Today I've encountered weird circumstances after sideloading Kodi to the Amazon Fire TV Stick 4K (and to re-check this issue installed Kodi Leia on my Samsung Tablet) and installing the addon.

With LibreELEC, once clicked on, the addon loads in an instant and shows channels, live, congress and what not.

On the Amazon stick (running Android 7.1.2) and my Tablet (running Android 9) the Addon opens but keeps on loading for a long time before showing anything at all.

Next click on any entry and this repeats over and over again, loading for several minutes before anything shows up.

All my network equipment uses Pi-hole as DNS, I looked up the query log, but nothing is blocked. So, I've ran out of ideas now.

Any help is appreciated. 🙂

**Comment by TobiX** [comment]
Yes, I noticed this too yesterday, the performance wasn't that bad before. Will try to investigate tomorrow...

**Comment by TobiX** [comment]
This seems to be a IPv6 connectivity problem with `media.ccc.de` at the moment... I'll try to find someone to fix that

**Comment by TobiX** [comment]
IPv6 connectivity for `media.ccc.de` is restored, so performance should be fine on all platforms again!

**Comment by x2k13** [comment]
Thanks, working again! @TobiX
