### ISSUE TITLE
Incompatible with Kodi 19.0

### ISSUE THREAD

**Issue by mase76** [voc/plugin.video.media-ccc-de#29]
Hi!
This addon is marked as incompatible with Kodi 19.0, which is in beta state now.

**Comment by TobiX** [comment]
It is basically compatible, I just need to find the time to do a bit of clean-up and push a release.

**Comment by TobiX** [comment]
See the https://github.com/voc/plugin.video.media-ccc-de/tree/matrix branch. When https://github.com/xbmc/repo-plugins/pull/3279 get merged, it will be available from the Kodi add-on repository.

**Comment by mase76** [comment]
This works!

**Comment by TobiX** [comment]
A version has been published to the official Kodi 19 (Matrix) repository. I'll keep the `matrix` branch around until I stop supporting older Kodi releases, but it will probably not be up-to-date with the `main` branch (unless I'm currently preparing a release) most of the time.
