### ISSUE TITLE
dependency script.module.idna could not be installed 

### ISSUE THREAD

**Issue by Wikinaut** [voc/plugin.video.media-ccc-de#36]
I wanted to install the media.ccc.de addon on KODI 18.7, but the script.module.idna dependency is not fullfilled.

Please can you assist, what's broken, what is needed to fix here? I found few information elsewhere but I am unsure whether it is a system issue or an addon-issue.

**Comment by Wikinaut** [comment]
Workaround:

I installed that apparently missing module directly from https://mirrors.kodi.tv/addons/krypton/script.module.idna/ .
Then the media.ccc.de Addon can be installed, as the dependency is now fullfilled.

Question to the maintainer: shouldn't this be done automatically when media.ccc.de is installed?

**Comment by TobiX** [comment]
This seems to be a bug in Kodi's repository, which doesn't include the `script.module.idna` at the moment. See https://forum.kodi.tv/showthread.php?tid=360198

**Comment by Wikinaut** [comment]
Danke für Klarstellung, ich vermutete das auch.
