### ISSUE TITLE
All #rc3 (Remote Chaos Experience congress 27.-30.12.2020) recordings are missing

### ISSUE THREAD

**Issue by Wikinaut** [voc/plugin.video.media-ccc-de#37]
Apparently, all rc3 recordings are still missing – why?

**Comment by TobiX** [comment]
They are in the same place as on media.ccc.de: "Conferences" -> "Remote Chaos Experience"

**Comment by Wikinaut** [comment]
äh, why not under "Congress" ?

**Comment by TobiX** [comment]
Because someone somewhere decided that it shouldn't be under "Congress"? This plugin just consumes the media.ccc.de API - I personally am not involved with recording & releasing, so you have to ask someone else to find out why it was put there...

**Comment by derchrisuk** [comment]
Because rC3 is not Congress
