### ISSUE TITLE
Relive

### ISSUE THREAD

**Issue by cy8aer** [voc/plugin.video.media-ccc-de#38]
It would be nice to have access to Relive too (e.g. https://streaming.media.ccc.de/rc3/relive)

**Comment by cy8aer** [comment]
oups it is in https://github.com/voc/plugin.video.media-ccc-de/pull/34

**Comment by cy8aer** [comment]
hm the upstream plugin for libreelec/leila seems to be too old. Uploaded git main and it works.

**Comment by TobiX** [comment]
I forgot to cut a new release after merging relive support, sorry...
