### ISSUE TITLE
Stream stops after ~5 minutes

### ISSUE THREAD

**Issue by Lumiukko** [voc/plugin.video.media-ccc-de#45]
I was recently watching a stream from 37C3 on Kodi 20.x using this addon and it stopped every 5 minutes or so. After restarting it, it resumed from that time it stopped correctly, but 5 minutes later it stopped again, and again.

There was no error message.

Has anyone else have this issue, or is there anything I can do to narrow it down?

**Comment by TobiX** [comment]
That's really strange. FTR: The plugin has no control over video playback at all. When you select a video, the HTTPS URL (for example https://cdn.media.ccc.de/congress/2023/h264-hd/37c3-11993-deu-eng-Toniebox_Reverse_Engineering_hd.mp4) is passed to Kodi's video playback engine, which streams it directly from one of the CDN nodes (See https://cdn.media.ccc.de/congress/2023/h264-hd/37c3-11993-deu-eng-Toniebox_Reverse_Engineering_hd.mp4?mirrorlist for a list of active mirrors per file).

This might be a problem with the connection from you to the nearest mirror. Do fetches with wget/curl or from a browser work?

**Comment by TobiX** [comment]
Not reproducible and probably not a problem with the plugin, closing for now. Feel free to reopen if you have new insights.
